#
# https://github.com/P3TERX/Actions-OpenWrt
#
name: OpenWrt Builder
on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 查看工作空间
        uses: actions/checkout@main

      - name: 初始化编译环境
        uses: P3TERX/setup-openwrt-build-env@main

      - name: 克隆源码
        uses: P3TERX/clone-openwrt-source@main

      - name: 加载自定义信息源
        run: |
          chmod +x ${{ env.DIY_P1_SH }}
          ./${{ env.DIY_P1_SH }}

      - name: 更新信息流 feeds
        run: ./scripts/feeds update -a && ./scripts/feeds install -a

      - name: 加载自定义配置
        uses: P3TERX/load-openwrt-config@main

      - name: 下载软件包
        uses: P3TERX/download-openwrt-packages@main

      - name: 编译固件
        uses: P3TERX/build-openwrt@main

      - name: 执行DIY part2
        run: |
          chmod +x ${{ env.DIY_P2_SH }}
          ./${{ env.DIY_P2_SH }}

      - name: 检查空间
        run: df -h

      - name: 整理文件
        run: |
          if [ -d openwrt/bin/targets/*/* ]; then
            cd openwrt/bin/targets/*/*
          fi

      - name: 上传固件目录
        uses: actions/upload-artifact@main
        with:
          name: KiJueWrt_bin
          path: openwrt/bin

      - name: 结账
        uses: P3TERX/post-openwrt-build@main

      - name: 完成工作
        run: echo "KiJueWrt编译结束"
